### ISSUE TITLE
Complex/multiple transforms

### ISSUE THREAD

**Issue by phil-linnell** [phil-linnell/ornithopter#13]

**Comment by arnau** [comment]
I'm wondering if our current assumption of `transform` properties is actually true.

We have a starting point like:

```css
transform: translateX(0, 100px)
```

And then we expect `processMultiple()` to receive something like:

```js
processMultiple([["transform", ["0", "100px"], "translateX"]])
```

To be fair, the issue comes from `process()`, but the point is, we are saying we will parse something like
`transform: translateX(0, 100px)` to become `["transform", ["0", "100px"], "translateX"]` instead of do something like `["transform", ["translateX(0)", "translateX(100px)"]]`.

We might want to spend some time with the postCSS side of things to see what approach is more natural.  If my guess is right the second option will be more straightforward, which will simplify the internals of `process()`.
